import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {spawn} from 'node:child_process';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {ROOT} from './build.mjs';
import {loadBook} from './build.mjs';
import reading from './reading.cjs';
const require=createRequire(import.meta.url);
const corpus=await loadBook(),allEntries=corpus.sections.flatMap(s=>s.entries),total=allEntries.length;
const licenseTexts={notice:await readFile(path.join(ROOT,'licenses/NOTICE.txt'),'utf8'),code:await readFile(path.join(ROOT,'LICENSE-CODE'),'utf8'),content:await readFile(path.join(ROOT,'LICENSE'),'utf8')};
let pw;
try{pw=require('playwright');}catch{pw=await import(pathToFileURL(path.resolve(path.dirname(process.execPath),'../node_modules/playwright/index.mjs')).href);}
const server=spawn(process.execPath,['tools/serve.mjs'],{cwd:ROOT,windowsHide:true,env:{...process.env,PORT:'4187'},stdio:['ignore','pipe','pipe']});
let browser;const results=[];const errors=[];
const note=(name)=>{results.push({name,status:'passed'});console.log('PASS '+name);};
try{
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('server timeout')),15000);server.once('error',reject);server.stdout.once('data',()=>{clearTimeout(timer);resolve();});server.stderr.on('data',d=>errors.push(String(d)));});
  browser=await pw.chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100}});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const requests=[];page.on('request',r=>requests.push(r.url()));
  await page.goto('http://127.0.0.1:4187');await page.waitForSelector('body[data-ready="true"]');
  assert.equal(await page.locator('article.card:visible').count(),total);note('实时页面显示全部正文条目');
  assert.equal(await page.locator('#quality, #quality-status, a[href*="evaluation/"]').count(),0);assert(!requests.some(url=>/evaluation\/|dist\/quality\.json|skills\/train-better-guide\/SKILL/.test(url)));note('阅读页面不显示或请求内部评测资料');
  await mkdir(path.join(ROOT,'docs/qa'),{recursive:true});await page.screenshot({path:path.join(ROOT,'docs/qa/desktop.png')});
  await page.locator('#q').fill('蛋白粉 必须');assert(await page.locator('#e-3-6').isVisible());assert.equal(await page.locator('article:visible').count(),allEntries.filter(e=>e.hay.includes('蛋白粉')&&e.hay.includes('必须')).length);note('关键词与常见问法搜索');
  await page.locator('#reset').click();await page.locator('button[data-dim="sec"][data-v="3"]').click();await page.locator('button[data-dim="money"][data-v="0"]').click();assert.equal(await page.locator('article:visible').count(),allEntries.filter(e=>e.sec==='3'&&e.money==='0').length);note('章节与成本组合筛选');
  await page.locator('#q').fill('完全不存在的关键词');assert(await page.locator('#empty').isVisible());await page.locator('#reset-empty').click();assert.equal(await page.locator('article:visible').count(),total);note('空结果与清空筛选');
  assert(await page.locator('#sort option[value="value"]').evaluate(n=>n.disabled));await page.locator('button[data-dim="lens"][data-v="增肌"]').click();await page.locator('#sort').selectOption('value');assert(await page.locator('#sorted').isVisible());const sortedIds=await page.locator('#sorted article').evaluateAll(ns=>ns.map(n=>n.dataset.id));assert(sortedIds.includes('TB-01-03'));note('单目标排序保持固定编号');
  await page.locator('button[data-dim="lens"][data-v="力量"]').click();assert.equal(await page.locator('#sort').inputValue(),'chapter');note('跨目标禁止合并排名');
  await page.locator('#reset').click();await page.locator('#dispute').check();assert.equal(await page.locator('article:visible').count(),allEntries.filter(e=>e.dispute).length);note('争议筛选');
  await page.goto('http://127.0.0.1:4187/?q=蛋白粉#e-4-6');await page.waitForSelector('body[data-ready="true"]');assert(await page.locator('#e-4-6').isVisible());assert.equal(await page.locator('#q').inputValue(),'');note('被筛选隐藏的深链接可跳转');
  await page.locator('#theme').click();assert(await page.locator('html').evaluate(n=>n.classList.contains('dark')));await page.reload();await page.waitForSelector('body[data-ready="true"]');assert(await page.locator('html').evaluate(n=>n.classList.contains('dark')));await page.locator('#theme').click();note('主题切换与持久化');
  await page.goto('http://127.0.0.1:4187');await page.waitForSelector('body[data-ready="true"]');
  for(const route of reading.routes){await page.locator(`[data-route="${route.id}"]`).click();assert.equal(await page.locator('article:visible').count(),route.ids.length);const ids=await page.locator('article:visible').evaluateAll(ns=>ns.map(n=>n.dataset.id));assert.deepEqual([...ids].sort(),[...route.ids].sort());assert.equal(await page.locator('#route-steps li').count(),route.ids.length);}
  await page.locator('[data-route="start"]').click();await page.reload();await page.waitForSelector('body[data-ready="true"]');assert.equal(await page.locator('article:visible').count(),4);assert.equal(await page.locator('[data-route="start"]').getAttribute('aria-pressed'),'true');note('六组导读引用、阅读顺序和刷新状态');
  await page.locator('#route-next').click();assert.equal(new URL(page.url()).hash,'#e-1-1');assert.equal(await page.locator('#e-1-1').evaluate(n=>document.activeElement===n),true);
  await page.locator('#e-1-1 [data-reading="saved"]').click();await page.locator('#e-1-1 [data-reading="read"]').click();assert((await page.locator('#route-steps li').first().textContent()).includes('已读'));assert((await page.locator('#route-next').textContent()).includes('重量'));await page.reload();await page.waitForSelector('body[data-ready="true"]');assert.equal(await page.locator('#e-1-1 [data-reading="saved"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#e-1-1 [data-reading="read"]').getAttribute('aria-pressed'),'true');note('收藏、已读、下一条与刷新保存');
  await page.locator('[data-panel="library"]').click();await page.locator('[data-readview="saved"]').click();assert.equal(await page.locator('article:visible').count(),1);await page.locator('#e-1-1 [data-reading="saved"]').click();assert(await page.locator('#empty').isVisible());await page.locator('#reset-empty').click();assert.equal(await page.locator('article:visible').count(),total);assert.equal(await page.locator('#e-1-1 [data-reading="read"]').getAttribute('aria-pressed'),'true');await page.locator('[data-readview="unread"]').click();assert.equal(await page.locator('article:visible').count(),total-1);assert(!(await page.locator('#e-1-1').isVisible()));await page.locator('#reset').click();note('阅读状态筛选、取消收藏空结果与清空不丢进度');
  await page.locator('#e-1-1 [data-reading="saved"]').click();await page.locator('[data-panel="library"]').click();
  const imported={...reading.empty(),saved:['TB-03-06','TB-99-99'],read:['TB-02-01'],lastId:'TB-03-06'};
  await page.locator('#reading-file').setInputFiles({name:'reading.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>document.getElementById('reading-message').textContent.startsWith('已合并'));
  assert((await page.locator('#reading-count').textContent()).includes(`已读 2 / ${total} 条 · 收藏 2 条`));assert((await page.locator('#resume').textContent()).includes('蛋白粉'));
  const download=page.waitForEvent('download');await page.locator('#reading-export').click();const downloaded=await download;await downloaded.saveAs(path.join(ROOT,'.cache/reading-backup.json'));
  const exported=JSON.parse(await page.evaluate(()=>localStorage.getItem('htb-reading-v1')));assert.deepEqual(new Set(exported.saved),new Set(['TB-01-01','TB-03-06']));assert.deepEqual(new Set(exported.read),new Set(['TB-01-01','TB-02-01']));note('备份导出、合并导入和未知编号处理');
  assert.deepEqual(JSON.parse(await readFile(path.join(ROOT,'.cache/reading-backup.json'),'utf8')),exported);
  await page.locator('#reading-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});await page.waitForFunction(()=>document.getElementById('reading-message').textContent.startsWith('未导入'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('htb-reading-v1')).saved.length),2);note('错误备份不会改写当前记录');
  await page.locator('[data-panel="myths"]').click();const book=await loadBook(),entries=book.sections.flatMap(s=>s.entries);
  for(const id of reading.myths){const e=entries.find(e=>e.id===id),myth=page.locator(`[data-myth="${id}"]`);await myth.locator(':scope > summary').click();assert.equal(await myth.locator('.human').textContent(),e.human);assert((await myth.textContent()).includes(e.note));assert((await myth.textContent()).includes(e.evidence));assert((await myth.locator('.src .body').textContent()).includes(e.src));}
  await page.locator('[data-myth="TB-05-01"] .myth-answer > a').click();assert.equal(new URL(page.url()).hash,'#e-5-1');assert(await page.locator('#e-5-1').isVisible());note('24项避坑结论、限制和来源与正文一致，完整条目可达');
  await page.locator('#e-5-1 .reading-back').click();assert(await page.locator('#library-panel').isVisible());await page.locator('#resume').click();assert.equal(new URL(page.url()).hash,'#e-5-1');assert.equal(await page.locator('#e-5-1 [data-reading="read"]').getAttribute('aria-pressed'),'false');note('返回阅读工具和继续阅读，不自动标记已读');
  const mirror=await context.newPage();mirror.on('pageerror',e=>errors.push(e.message));await mirror.goto('http://127.0.0.1:4187');await mirror.waitForSelector('body[data-ready="true"]');await page.locator('#e-5-1 [data-reading="saved"]').click();await mirror.waitForFunction(()=>document.querySelector('#e-5-1 [data-reading="saved"]').getAttribute('aria-pressed')==='true');await page.locator('#e-5-1 [data-reading="saved"]').click();await mirror.close();note('同源多窗口阅读记录同步');
  const denied=await browser.newContext();await denied.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}}));const deniedPage=await denied.newPage();deniedPage.on('pageerror',e=>errors.push(e.message));await deniedPage.goto('http://127.0.0.1:4187');await deniedPage.waitForSelector('body[data-ready="true"]');assert(await deniedPage.locator('#reading-notice').isVisible());await deniedPage.locator('#e-1-1 [data-reading="saved"]').click();assert.equal(await deniedPage.locator('#e-1-1 [data-reading="saved"]').getAttribute('aria-pressed'),'true');await denied.close();note('浏览器禁用存储时仍可使用并提示备份');
  await page.goto('http://127.0.0.1:4187');await page.waitForSelector('body[data-ready="true"]');await page.screenshot({path:path.join(ROOT,'docs/qa/desktop.png')});
  const mobile=await context.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.goto('http://127.0.0.1:4187');await mobile.waitForSelector('body[data-ready="true"]');assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('#menu').click();assert.equal(await mobile.locator('#menu').getAttribute('aria-expanded'),'true');await mobile.locator('button[data-dim="sec"][data-v="2"]').click();assert.equal(await mobile.locator('article:visible').count(),corpus.sections.find(s=>s.n==='2').entries.length);assert.equal(await mobile.locator('#menu').getAttribute('aria-expanded'),'false');await mobile.waitForFunction(()=>document.getElementById('sidebar').getBoundingClientRect().right<=1);assert(await mobile.locator('#sidebar').evaluate(n=>n.inert));await mobile.screenshot({path:path.join(ROOT,'docs/qa/mobile.png')});note('手机阅读、侧栏开关及无横向溢出');
  await mobile.locator('#jump-results').click();assert.equal(await mobile.locator('#toolbar').evaluate(n=>document.activeElement===n),true);await mobile.locator('#e-2-1 .reading-back').click();assert(await mobile.locator('#library-panel').isVisible());await mobile.locator('[data-panel="myths"]').click();await mobile.locator('[data-myth="TB-05-01"] > summary').click();assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('#theme').click();await mobile.locator('#reading-hub').scrollIntoViewIfNeeded();await mobile.screenshot({path:path.join(ROOT,'docs/qa/mobile-myths-dark.png'),animations:'disabled'});await mobile.locator('#theme').click();note('手机直达正文、返回工具及深色误区展开无溢出');
  await mobile.setViewportSize({width:960,height:900});await mobile.locator('#menu').click();await mobile.waitForFunction(()=>document.getElementById('sidebar').getBoundingClientRect().left>=-1);await mobile.locator('#menu').click();await mobile.waitForFunction(()=>document.getElementById('sidebar').getBoundingClientRect().right<=1);note('960像素边界侧栏可打开和关闭');
  const offlineContext=await browser.newContext({offline:true,viewport:{width:1280,height:900}});const offline=await offlineContext.newPage();const remote=[];offline.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url())});offline.on('pageerror',e=>errors.push(e.message));await offline.goto(pathToFileURL(path.join(ROOT,'dist/HowToTrainBetter.html')).href);await offline.waitForSelector('body[data-ready="true"]');assert.equal(await offline.locator('article:visible').count(),total);await offline.locator('#q').fill('空腹');assert(Number(await offline.locator('#cnt').textContent())>0);assert.equal(remote.length,0);await offline.screenshot({path:path.join(ROOT,'docs/qa/offline.png')});note('断网file打开、检索及零外部请求');
  await offline.locator('[data-route="busy"]').click();assert.equal(await offline.locator('article:visible').count(),4);await offline.locator('#e-1-2 [data-reading="saved"]').click();await offline.reload();await offline.waitForSelector('body[data-ready="true"]');assert.equal(await offline.locator('#e-1-2 [data-reading="saved"]').getAttribute('aria-pressed'),'true');await offline.locator('[data-panel="library"]').click();await offline.locator('#reading-file').setInputFiles(path.join(ROOT,'.cache/reading-backup.json'));await offline.waitForFunction(()=>document.getElementById('reading-message').textContent.startsWith('已合并'));await offline.locator('[data-readview="saved"]').click();assert.equal(await offline.locator('article:visible').count(),3);assert.equal(remote.length,0);note('离线导读、持久化与跨入口备份导入');
  const bad=await context.newPage();await bad.route('**/book/**',r=>r.fulfill({status:404,body:'missing'}));await bad.goto('http://127.0.0.1:4187');await bad.waitForSelector('body[data-ready="error"]');assert((await bad.locator('#status').textContent()).includes('读取正文失败'));note('缺失正文显示可理解的错误');
  assert.equal(await offline.locator('#quality, #quality-status, a[href*="evaluation/"]').count(),0);assert.equal(await offline.evaluate(()=>Object.hasOwn(window.__CORPUS__,'quality')),false);note('离线阅读文件不展示或内嵌评测数据');
  // New entries use existing search, links and record format.
  await page.locator('#reset').click();await page.locator('#q').fill('手表 热量');assert.equal(await page.locator('article:visible').getAttribute('data-id'),'TB-02-08');
  await page.goto('http://127.0.0.1:4187/?q=蛋白粉#e-5-8');await page.waitForSelector('body[data-ready="true"]');assert(await page.locator('#e-5-8').isVisible());assert.equal(await page.locator('#q').inputValue(),'');
  for(const e of allEntries.filter(e=>Number(e.n)>6))assert.equal(await page.locator('[data-id="'+e.id+'"] [data-reading="read"]').getAttribute('aria-pressed'),'false');note('新增条目可搜索跳转，旧备份导入后新条目仍未读');
  for(const target of [page,offline]){for(const key of ['notice','code','content'])assert.equal(await target.locator('#license-'+key).textContent(),licenseTexts[key]);assert.notEqual(await target.locator('article .human').first().evaluate(n=>getComputedStyle(n).userSelect),'none');await target.locator('#licensing > summary').click();assert(await target.locator('#license-notice').isVisible());await target.locator('#licensing details').first().locator('summary').click();assert(await target.locator('#license-code').isVisible());}
  assert.equal(remote.length,0);note('实时与断网离线许可范围、完整 CC 和 MIT 原文一致');
  await mobile.setViewportSize({width:390,height:844});await mobile.locator('#licensing > summary').click();await mobile.locator('#licensing details').last().locator('summary').click();assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('#licensing').scrollIntoViewIfNeeded();await mobile.screenshot({path:path.join(ROOT,'docs/qa/licenses-mobile.png')});note('手机展开完整许可仍无横向溢出');
  const missingLicense=await context.newPage();await missingLicense.route('**/LICENSE-CODE',r=>r.fulfill({status:404,body:'missing'}));await missingLicense.goto('http://127.0.0.1:4187');await missingLicense.waitForSelector('body[data-ready="true"]');assert((await missingLicense.locator('#license-status').textContent()).includes('读取失败'));assert.equal(await missingLicense.locator('article:visible').count(),total);await missingLicense.close();note('许可读取错误明确提示且不阻断正文');
  await page.goto('http://127.0.0.1:4187');await page.waitForSelector('body[data-ready="true"]');
  await page.locator('[data-panel="catalog"]').click();assert.equal(await page.locator('#catalog-list li').count(),total);assert.equal(await page.locator('#catalog-list details').count(),8);
  await page.locator('#q').fill('蛋白粉');await page.locator('#catalog-list details').nth(4).locator('summary').click();await page.locator('#catalog-list a[href="#e-5-10"]').click();assert(await page.locator('#e-5-10').isVisible());assert.equal(await page.locator('#q').inputValue(),'');note('全部问题覆盖94条，跳转可清除遮挡条目的筛选');
  await page.locator('#e-5-10 .src > summary').click();await page.locator('#e-5-10 a[href="#source-S24"]').click();assert(await page.locator('#sources').evaluate(n=>n.open));assert(await page.locator('#source-S24').evaluate(n=>n.open));assert.equal(await page.locator('#source-list > details').count(),73);await page.locator('#source-S24 a[href="#e-5-10"]').click();assert.equal(new URL(page.url()).hash,'#e-5-10');note('来源编号展开对应资料并可返回相关条目');
  await page.locator('#e-5-10 .share-actions button').first().click();assert(await page.locator('#reader-dialog').isVisible());const excerpt=await page.locator('#reader-copy-text').inputValue();const newEntry=allEntries.find(e=>e.id==='TB-05-10');for(const value of [newEntry.note,newEntry.src,newEntry.evidence,'CC BY-NC 4.0','v0.9.0'])assert(excerpt.includes(value));await page.locator('#reader-dialog-close').click();note('分享文字保留证据、限制、来源和许可');
  await page.locator('#e-5-10 .share-actions button').last().click();assert((await page.locator('#reader-copy-text').inputValue()).includes('TB-05-10'));assert((await page.locator('#reader-dialog-hint').textContent()).includes('不会自动发送'));await page.keyboard.press('Escape');assert(!(await page.locator('#reader-dialog').isVisible()));note('反馈模板注明条目且不自动提交，Escape可关闭');
  await page.locator('#q').fill('组间');const printed=await page.locator('article:visible').count();assert(printed>0&&printed<total);await page.evaluate(()=>dispatchEvent(new Event('beforeprint')));await page.emulateMedia({media:'print'});assert.equal(await page.locator('article:visible').count(),printed);assert(!(await page.locator('.nav').isVisible()));assert(await page.locator('.print-license').isVisible());assert(await page.locator('article:visible .src .body').first().isVisible());await page.pdf({path:path.join(ROOT,'docs/qa/print-sample.pdf'),format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});await page.evaluate(()=>dispatchEvent(new Event('afterprint')));note('打印保留当前筛选、完整来源和署名许可');
  await mobile.goto('http://127.0.0.1:4187');await mobile.waitForSelector('body[data-ready="true"]');await mobile.locator('[data-panel="catalog"]').click();assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('#catalog-panel').scrollIntoViewIfNeeded();await mobile.screenshot({path:path.join(ROOT,'docs/qa/catalog-mobile.png')});await mobile.locator('#catalog-list a').first().click();await mobile.locator('#e-1-1 .share-actions button').first().click();assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:path.join(ROOT,'docs/qa/share-mobile.png')});await mobile.locator('#reader-dialog-close').click();note('手机问题目录与复制窗口无横向溢出');
  await offline.locator('[data-panel="catalog"]').click();assert.equal(await offline.locator('#catalog-list li').count(),total);await offline.locator('#catalog-list a').first().click();await offline.locator('#e-1-1 .share-actions button').first().click();assert((await offline.locator('#reader-copy-text').inputValue()).includes('TB-01-01'));await offline.locator('#reader-copy').click();assert((await offline.locator('#reader-copy-status').textContent()).length>0);await offline.locator('#reader-dialog-close').click();assert.equal(remote.length,0);note('断网目录及复制工具可用，剪贴板失败时提供手动复制');

  await page.locator('#reset').click();await page.locator('[data-panel="supplements"]').click();assert(await page.locator('#supplements-panel').isVisible());assert(!(await page.locator('#catalog-panel').isVisible()));assert.equal(await page.locator('.supplement-summary:visible').count(),20);
  for(const [g,count] of [['A',3],['B',11],['C',6]]){await page.locator(`[data-supplement-grade="${g}"]`).click();assert.equal(await page.locator('.supplement-summary:visible').count(),count);}
  await page.locator('[data-supplement-grade=""]').click();assert.equal(await page.locator('.supplement-summary:visible').count(),20);await page.locator('#supplement-list a[href="#e-6-15"]').click();assert(await page.locator('#e-6-15').isVisible());note('20类补剂按推荐度筛选，条件与限制保留，详情可达');
  await page.locator('[data-panel="supplements"]').click();await page.locator('[data-supplement-grade="C"]').click();assert.equal(await page.locator('.comparison-summary:visible').count(),1);assert((await page.locator('#comparison-list').textContent()).includes('选购比较'));assert(!(await page.locator('#comparison-list').textContent()).includes('推荐 B'));await page.locator('#comparison-list a').click();assert(await page.locator('#e-6-19').isVisible());note('选购比较独立展示，不参与ABC推荐筛选');
  await page.locator('#reset').click();await page.locator('.audience-entries a').first().click();assert(await page.locator('#e-1-11').isVisible());await page.locator('.audience-entries a').nth(1).click();assert(await page.locator('#e-7-13').isVisible());assert((await page.locator('#author > summary').textContent()).includes('栗子豪'));await page.locator('#author > summary').click();assert(await page.locator('#author-body').isVisible());assert((await page.locator('#author-body').textContent()).includes('记录表现'));assert.equal(await page.locator('#author-body a').count(),0);note('双人群入口可达，作者介绍可展开，未提供联系方式时不显示占位链接');
  await page.locator('[data-panel="advanced"]').click();assert.equal(await page.locator('#advanced-list li').count(),13);assert(!(await page.locator('#supplements-panel').isVisible()));await page.locator('#advanced-list a[href="#e-7-4"]').click();assert(await page.locator('#e-7-4').isVisible());note('13条进阶目录及TUT跳转');
  await page.locator('#q').fill('咖啡因');await page.locator('button[data-dim="lens"][data-v="运动表现"]').click();assert(await page.locator('#e-6-3').isVisible());await page.locator('#e-6-3 .share-actions button').first().click();const supplementText=await page.locator('#reader-copy-text').inputValue();assert(supplementText.includes('补剂推荐：A'));assert(supplementText.includes('不等于证据等级'));assert(supplementText.includes('适用人群'));await page.locator('#reader-dialog-close').click();await page.locator('#reset').click();note('运动表现单独筛选，补剂分享保留推荐条件');
  await mobile.locator('[data-panel="supplements"]').click();assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('#supplements-panel').scrollIntoViewIfNeeded();await mobile.screenshot({path:path.join(ROOT,'docs/qa/supplements-mobile.png')});await mobile.locator('[data-panel="advanced"]').click();assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('#advanced-panel').scrollIntoViewIfNeeded();await mobile.screenshot({path:path.join(ROOT,'docs/qa/advanced-mobile.png')});note('手机补剂与进阶入口无横向溢出');
  await offline.locator('[data-panel="supplements"]').click();await offline.locator('[data-supplement-grade="B"]').click();assert.equal(await offline.locator('.supplement-summary:visible').count(),11);await offline.locator('[data-panel="advanced"]').click();await offline.locator('#advanced-list a[href="#e-7-4"]').click();assert(await offline.locator('#e-7-4').isVisible());assert.equal(remote.length,0);note('新专题断网可读、筛选、跳转且无外部请求');

  assert.deepEqual(errors,[]);note('无浏览器脚本错误');
  await writeFile(path.join(ROOT,'docs/qa/browser-results.json'),JSON.stringify({date:new Date().toISOString().slice(0,10),browser:await browser.version(),results,errors},null,2)+'\n');
}finally{if(browser)await browser.close();server.kill();}
